# On push, run the action-wporg-validator workflow.
name: Lint and Test
on: [push]
permissions:
  contents: write
jobs:
  validate-readme-spacing:
    name: Validate README Spacing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pantheon-systems/validate-readme-spacing@v1
  wporg-validation:
    name: WP.org Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: WP.org Validator
        uses: pantheon-systems/action-wporg-validator@1.0.0
        with:
          type: plugin
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: shalior/wordpress-phpcs-action@v1
        with:
          github_token: ${{ github.token }}
          use_default_configuration_file: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "PHPCBF: Fix coding standards"
          commit_options: '--no-verify'
          branch: ${{ github.ref }}
          commit_user_name: "Pantheon Robot"
          commit_user_email: "bot@getpantheon.io"
